# Generated by Django 3.1.1 on 2021-04-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('volume', models.FloatField(default=0)),
                ('cprsystem', models.JSONField(default=dict)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrumenttype')),
            ],
        ),
    ]
