# Generated by Django 3.1.1 on 2021-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cprsystem',
            field=models.JSONField(default=dict),
        ),
    ]
