# Generated by Django 3.1.1 on 2021-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
