# Generated by Django 3.1.1 on 2021-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrument_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
