# Generated by Django 3.1.1 on 2021-04-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriber_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
